version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: panameconsultingDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fXLfojVGjUGRXhkGcPjgqlJGFVBfIWAK
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: backend
    ports:
      - "10000:10000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:fXLfojVGjUGRXhkGcPjgqlJGFVBfIWAK@postgres.railway.internal:5432/railway?schema=public

volumes:
  postgres_data: