version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    image: panameconsultingbackend:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    restart: unless-stopped
    
    # Vérifie si l'API répond bien
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"