export const AuthConstants = {
  ACCESS_TOKEN_EXPIRATION_MS: 15 * 60 * 1000,
  ACCESS_TOKEN_EXPIRATION: '15m',

  REFRESH_TOKEN_EXPIRATION_MS: 7 * 24 * 60 * 60 * 1000,
  REFRESH_TOKEN_EXPIRATION: '7d',

  // remember_me : 14 jours
  REMEMBER_ME_EXPIRATION_MS: 14 * 24 * 60 * 60 * 1000,
  REMEMBER_ME_EXPIRATION: '14d',

  MAX_ACTIVE_SESSIONS_PER_USER: 2,
  MAX_REFRESH_TOKEN_ROTATION: 10,
  INACTIVITY_DAYS_BEFORE_CLEANUP: 30,
  SESSION_INACTIVITY_LIMIT_MS: 60 * 60 * 1000, // 1 heure
  SESSION_MAX_DURATION_MS: 30 * 24 * 60 * 60 * 1000, // 30 jours

  // Valeurs alignées sur l'enum Prisma RevocationReason
  // À l'usage : toujours RevocationReason.X depuis @prisma/client, jamais ces strings directement
  REVOCATION_REASONS: {
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    MANUAL_LOGOUT: 'MANUAL_LOGOUT',
    PASSWORD_CHANGED: 'PASSWORD_CHANGED',
    ADMIN_REVOKE: 'ADMIN_REVOKE',
    MANUAL_REVOKE: 'MANUAL_REVOKE',
    MAX_SESSIONS_REACHED: 'MAX_SESSIONS_REACHED',
    INACTIVITY: 'INACTIVITY',
    REMEMBER_ME_EXPIRED: 'REMEMBER_ME_EXPIRED',
    SESSION_MAX_AGE: 'SESSION_MAX_AGE',
  },
} as const;
